/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tela;

import classe.ConverteMoeda;
import classe.bdConexao;
import classe.letraPen;
import java.awt.Image;
import static java.lang.Thread.sleep;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Luiz Otavio
 */
public class main extends javax.swing.JFrame {
    
    bdConexao objbd = new bdConexao();
    ConverteMoeda cm = new ConverteMoeda();
    letraPen letra = new letraPen();
    
    int num1 = 0, num2 = 0, num3 = 0, x = 0, valtotal = 0, valinserido = 0, tentativa = 0, tentativainserida = 0, ganho = 0, ganhorandomico = 0;
    boolean control;
    String nome = "", pen = ""; 
    
    public String EMPTY = "";
    
    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bckpainel = new javax.swing.JPanel();
        lbfigura2 = new javax.swing.JLabel();
        lbfigura1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbrestante = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lbganho = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lbfigura3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbalavancaup = new javax.swing.JLabel();
        lbalavancadown = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbtentativa = new javax.swing.JLabel();
        lbtitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbmachine = new javax.swing.JLabel();
        lbval1 = new javax.swing.JLabel();
        lbval2 = new javax.swing.JLabel();
        lbval3 = new javax.swing.JLabel();
        lbobs = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inputNome = new javax.swing.JTextField();
        btnSalva = new javax.swing.JButton();
        btnEdita = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(null);
        setMinimumSize(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        bckpainel.setBackground(new java.awt.Color(255, 255, 255));
        bckpainel.setMinimumSize(new java.awt.Dimension(1024, 600));
        bckpainel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbfigura2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbfigura2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bckpainel.add(lbfigura2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 350, 100, 100));

        lbfigura1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbfigura1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bckpainel.add(lbfigura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 350, 80, 100));

        lbrestante.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbrestante.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lbrestante, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbrestante, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        bckpainel.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 530, 140, 30));

        lbganho.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lbganho.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbganho.setText("R$ 0,00");
        lbganho.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbganho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbganhoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbganho, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbganho, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
        );

        bckpainel.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 530, 140, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("GANHO");
        bckpainel.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 510, 140, -1));

        lbfigura3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lbfigura3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bckpainel.add(lbfigura3, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 350, 90, 100));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("RESTANTE");
        bckpainel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 510, 140, -1));

        lbalavancaup.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbalavancaup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbalavancaupMouseClicked(evt);
            }
        });
        bckpainel.add(lbalavancaup, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 140, 90, 520));

        lbalavancadown.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbalavancadown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbalavancadownMouseClicked(evt);
            }
        });
        bckpainel.add(lbalavancadown, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 190, 90, 520));

        lbtentativa.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        lbtentativa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbtentativa.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbtentativa, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbtentativa, javax.swing.GroupLayout.DEFAULT_SIZE, 78, Short.MAX_VALUE)
                .addContainerGap())
        );

        bckpainel.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, -1, -1));
        bckpainel.add(lbtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 490, 250));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TENTATIVAS");
        bckpainel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 320, 100, 20));

        lbmachine.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        lbmachine.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/machine.png"))); // NOI18N
        bckpainel.add(lbmachine, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 120, -1, 452));

        lbval1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbval1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbval1MouseClicked(evt);
            }
        });
        bckpainel.add(lbval1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 170, 70));

        lbval2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbval2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbval2MouseClicked(evt);
            }
        });
        bckpainel.add(lbval2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 170, 70));

        lbval3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lbval3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbval3MouseClicked(evt);
            }
        });
        bckpainel.add(lbval3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, 170, 70));

        lbobs.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbobs.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbobs.setText("Obs* valor mínimo para tentativa: R$ 10,00");
        bckpainel.add(lbobs, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 390, 40));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Digite seu nome:");
        bckpainel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 150, 40));
        bckpainel.add(inputNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, 260, 20));

        btnSalva.setBackground(new java.awt.Color(51, 102, 255));
        btnSalva.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnSalva.setForeground(new java.awt.Color(255, 255, 255));
        btnSalva.setText("Salvar");
        btnSalva.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalvaMouseClicked(evt);
            }
        });
        bckpainel.add(btnSalva, new org.netbeans.lib.awtextra.AbsoluteConstraints(927, 53, 70, 30));

        btnEdita.setBackground(new java.awt.Color(0, 0, 0));
        btnEdita.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnEdita.setForeground(new java.awt.Color(255, 255, 255));
        btnEdita.setText("  Editar");
        btnEdita.setVisible(false);
        btnEdita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditaMouseClicked(evt);
            }
        });
        bckpainel.add(btnEdita, new org.netbeans.lib.awtextra.AbsoluteConstraints(841, 83, 80, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        jLabel4.setText("*Obrigatório / Mínimo de três letras");
        bckpainel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bckpainel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bckpainel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        pen = letra.pegaLetra();
        
        ImageIcon imgtitle = new ImageIcon(new ImageIcon(pen + ":\\cacaNiquel/\\src\\img\\title.jpg").getImage().getScaledInstance(lbtitle.getWidth(), lbtitle.getHeight(), Image.SCALE_DEFAULT));        
        lbtitle.setIcon(imgtitle);
        
        ImageIcon nota10 = new ImageIcon(new ImageIcon(pen + ":\\cacaNiquel\\src\\img\\nota10.jpg").getImage().getScaledInstance(lbval1.getWidth(), lbval1.getHeight(), Image.SCALE_DEFAULT));        
        lbval1.setIcon(nota10);
        
        ImageIcon nota20 = new ImageIcon(new ImageIcon(pen + ":\\cacaNiquel\\src\\img\\nota20.jpg").getImage().getScaledInstance(lbval2.getWidth(), lbval2.getHeight(), Image.SCALE_DEFAULT));        
        lbval2.setIcon(nota20);
        
        ImageIcon nota50 = new ImageIcon(new ImageIcon(pen + ":\\cacaNiquel\\src\\img\\nota50.jpg").getImage().getScaledInstance(lbval3.getWidth(), lbval3.getHeight(), Image.SCALE_DEFAULT));        
        lbval3.setIcon(nota50);
        
        ImageIcon alavancaup = new ImageIcon(new ImageIcon(pen + ":\\cacaNiquel\\src\\img\\alavancaup.png").getImage().getScaledInstance(lbalavancaup.getWidth(), lbalavancaup.getHeight(), Image.SCALE_DEFAULT));
        lbalavancaup.setIcon(alavancaup);
    }//GEN-LAST:event_formWindowOpened

    private void lbalavancadownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbalavancadownMouseClicked
        
    }//GEN-LAST:event_lbalavancadownMouseClicked

    private void lbval1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbval1MouseClicked
        if(tentativa == 0 && ganho > 0){
            JOptionPane.showMessageDialog(null, "Retire o prêmio antes de jogar novamente");
        }else{
            insereValor(10);
            insereTentativas();
        }
    }//GEN-LAST:event_lbval1MouseClicked

    private void lbval2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbval2MouseClicked
        if(tentativa == 0 && ganho > 0){
            JOptionPane.showMessageDialog(null, "Retire o prêmio antes de jogar novamente");
        }else{
            insereValor(20);
            insereTentativas();
        }
    }//GEN-LAST:event_lbval2MouseClicked

    private void lbval3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbval3MouseClicked
        if(tentativa == 0 && ganho > 0){
            JOptionPane.showMessageDialog(null, "Retire o prêmio antes de jogar novamente!");
        }else{
            insereValor(50);
            insereTentativas();
        }
    }//GEN-LAST:event_lbval3MouseClicked

    private void lbganhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbganhoMouseClicked
        if(control == true){           
            retiraGanho();
            control = false;
        }else if(ganho == 0){
            JOptionPane.showMessageDialog(rootPane, "Não há o que retirar \nVocê não gahou nada!");
        }else{
            JOptionPane.showMessageDialog(rootPane, "Espere a rodada acabar para retirar o prêmio!");
        }
    }//GEN-LAST:event_lbganhoMouseClicked

    private void lbalavancaupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbalavancaupMouseClicked
        ImageIcon alavancadown = new ImageIcon(new ImageIcon(pen + ":\\cacaNiquel\\src\\img\\alavancadown.png").getImage().getScaledInstance(lbalavancadown.getWidth(), lbalavancadown.getHeight(), Image.SCALE_DEFAULT));
        lbfigura1.setIcon(null);
        lbfigura2.setIcon(null);
        lbfigura3.setIcon(null);
        lbval1.setVisible(false);
        lbval2.setVisible(false);
        lbval3.setVisible(false);
        
        if(valtotal >= 10){
            if(nome.equals(EMPTY)){
                JOptionPane.showMessageDialog(rootPane, "Insira um nome antes de iniciar");
                lbval1.setVisible(true);
                lbval2.setVisible(true);
                lbval3.setVisible(true);
            }else{
                btnEdita.setVisible(false);
                ImageIcon imgtitle = new ImageIcon(new ImageIcon(pen + ":\\cacaNiquel/\\src\\img\\title.jpg").getImage().getScaledInstance(lbtitle.getWidth(), lbtitle.getHeight(), Image.SCALE_DEFAULT));     
                lbalavancaup.setVisible(false);
                lbtitle.setIcon(imgtitle);
                lbalavancadown.setIcon(alavancadown);
                lbalavancadown.setVisible(true);
                mudaFigura();
                tiraValor();
                tiraTentativas(); 
            }
        }else{ 
            lbval1.setVisible(true);
            lbval2.setVisible(true);
            lbval3.setVisible(true);
            ImageIcon imgtitle = new ImageIcon(new ImageIcon(pen + ":\\cacaNiquel/\\src\\img\\title.jpg").getImage().getScaledInstance(lbtitle.getWidth(), lbtitle.getHeight(), Image.SCALE_DEFAULT));        
            lbtitle.setIcon(imgtitle);
            JOptionPane.showMessageDialog(null, "valor mínimo: \n R$10,00 ");
        } 
    }//GEN-LAST:event_lbalavancaupMouseClicked

    private void btnSalvaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalvaMouseClicked
        nome = inputNome.getText();
            
        if(nome.length() < 3 || nome.equals(EMPTY)){
            JOptionPane.showMessageDialog(rootPane, "Número de letras insuficientes ou campo vazio detectado!");
            nome = "";
            inputNome.setText("");
            inputNome.requestFocus();
        }
        else{
            nome = inputNome.getText();
            inputNome.setEnabled(false);
            btnSalva.setVisible(false);
            btnEdita.setVisible(true);        
        }
    }//GEN-LAST:event_btnSalvaMouseClicked

    private void btnEditaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditaMouseClicked
        inputNome.setEnabled(true);
        btnSalva.setVisible(true);
        btnEdita.setVisible(false);
        nome = "";
    }//GEN-LAST:event_btnEditaMouseClicked

    public void mudaFigura(){
        new Thread(){
            public void run(){ 
                Random rand = new Random();

                while(x <= 15){
                    num1 = rand.nextInt(3) + 1;
                    x++;
                    ImageIcon figura = new ImageIcon(new ImageIcon(pen + ":\\cacaNiquel\\src\\img\\figura" + num1 + ".png").getImage().getScaledInstance(lbfigura1.getWidth(), lbfigura1.getHeight(), Image.SCALE_DEFAULT));        
                    lbfigura1.setIcon(figura);

                    try {
                       sleep(155);
                    } catch(Exception e){
                       ;
                    }
                }

                x = 0;

                while(x <= 15){
                    num2 = rand.nextInt(3) + 1;
                    x++;
                    ImageIcon figura = new ImageIcon(new ImageIcon(pen + ":\\cacaNiquel\\src\\img\\figura" + num2 + ".png").getImage().getScaledInstance(lbfigura1.getWidth(), lbfigura1.getHeight(), Image.SCALE_DEFAULT));        
                    lbfigura2.setIcon(figura);

                    try {
                        sleep(155);
                    } catch(Exception e){
                        ;
                    }
                }

                x = 0;

                while(x <= 15){
                    num3 = rand.nextInt(3) + 1;
                    x++;
                    ImageIcon figura = new ImageIcon(new ImageIcon(pen + ":\\cacaNiquel/\\src\\img\\figura" + num3 + ".png").getImage().getScaledInstance(lbfigura1.getWidth(), lbfigura1.getHeight(), Image.SCALE_DEFAULT));        
                    lbfigura3.setIcon(figura);

                    try {
                        sleep(155);
                    } catch(Exception e){
                       ;
                    }
                }
                
                x = 0;
                lbalavancadown.setIcon(null); 
               
                if(num1 == num2 && num2 == num3){
                    Random randganho = new Random();
                    ganhorandomico = randganho.nextInt(1000);
                }               
                
                if(num1 == 1 & num2 == 1 & num3 == 1){
                    ganho = ganho + ganhorandomico;
                    lbganho.setText(cm.ConvMoeda(String.valueOf(ganho)));
                    ImageIcon winnerimg = new ImageIcon(new ImageIcon(pen + ":\\cacaNiquel/\\src\\img\\winner.jpg").getImage().getScaledInstance(lbtitle.getWidth(), lbtitle.getHeight(), Image.SCALE_DEFAULT));        
                    lbtitle.setIcon(winnerimg);
                }if(num1 == 2 & num2 == 2 & num3 == 2){
                    ganho = ganho + 50 + (valtotal * 2) + + ganhorandomico;
                    lbganho.setText(cm.ConvMoeda(String.valueOf(ganho)));    
                    ImageIcon winnerimg = new ImageIcon(new ImageIcon(pen + ":\\cacaNiquel/\\src\\img\\winner.jpg").getImage().getScaledInstance(lbtitle.getWidth(), lbtitle.getHeight(), Image.SCALE_DEFAULT));        
                    lbtitle.setIcon(winnerimg);
                }if(num1 == 3 & num2 == 3 & num3 == 3){
                    ganho = (ganho + 50) + (valtotal * 3) + + ganhorandomico;
                    lbganho.setText(cm.ConvMoeda(String.valueOf(ganho))); 
                    ImageIcon winnerimg = new ImageIcon(new ImageIcon(pen + ":\\cacaNiquel/\\src\\img\\winner.jpg").getImage().getScaledInstance(lbtitle.getWidth(), lbtitle.getHeight(), Image.SCALE_DEFAULT));        
                    lbtitle.setIcon(winnerimg);
                } 
                
                if(valtotal == 0 && tentativa == 0){
                    if(valinserido != 0 && tentativainserida !=0){
                        insereBD();
                        control = true;
                    }
                    try {
                       sleep(350);
                    } catch(Exception e){
                       ;
                    }
                      
                    ImageIcon icon = new ImageIcon(new ImageIcon(pen + ":\\cacaNiquel/\\src\\img\\title.jpg").getImage().getScaledInstance(lbtitle.getWidth(), lbtitle.getHeight(), Image.SCALE_DEFAULT));
                      
                    lbval1.setVisible(true);
                    lbval2.setVisible(true);
                    lbval3.setVisible(true);
                  
                    lbfigura1.setIcon(null);
                    lbfigura2.setIcon(null);
                    lbfigura3.setIcon(null);
                    nome = "";
                    inputNome.setText("");
                    inputNome.setEnabled(true);
                    btnSalva.setVisible(true);
                    lbtitle.setIcon(icon);
                }
                lbalavancadown.setVisible(false);
                lbalavancaup.setVisible(true);                      
            }  
        }.start(); 
    }
    
    private void insereValor(int val){
        valtotal += val;
        valinserido += val;
        lbrestante.setText(cm.ConvMoeda(String.valueOf(valtotal)));
        val = 0;
    }
    
    private void tiraValor(){
        valtotal = valtotal - 10;
        lbrestante.setText(cm.ConvMoeda(String.valueOf(valtotal)));
    }
    
    private void insereTentativas(){
        tentativa = valtotal / 10;
        tentativainserida = tentativa;
        lbtentativa.setText(String.valueOf(tentativa));
    }
    
    private void tiraTentativas(){
        tentativa -= 1;
        lbtentativa.setText(String.valueOf(tentativa));
    }
    
    private void retiraGanho(){
        if(tentativa == 0 && valtotal == 0){
            lbganho.setText("R$ 0,00");
            ganho = 0;
        }
    }
    
    private void insereBD(){
        String sql = "INSERT INTO jogada VALUES (null, '" + nome + "', '" + valinserido + "', '" + tentativainserida + "', 'R$" + ganho + ",00', NOW(), NOW());";
        
        try{
            objbd.conectar();
            objbd.runSQL(sql);
        }
        catch(Exception e){
            System.out.println(e.getMessage());
        }
        
        valinserido = 0;
        tentativainserida = 0;        
    }
        
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bckpainel;
    private javax.swing.JButton btnEdita;
    private javax.swing.JButton btnSalva;
    private javax.swing.JTextField inputNome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbalavancadown;
    private javax.swing.JLabel lbalavancaup;
    private javax.swing.JLabel lbfigura1;
    private javax.swing.JLabel lbfigura2;
    private javax.swing.JLabel lbfigura3;
    private javax.swing.JLabel lbganho;
    private javax.swing.JLabel lbmachine;
    private javax.swing.JLabel lbobs;
    private javax.swing.JLabel lbrestante;
    private javax.swing.JLabel lbtentativa;
    private javax.swing.JLabel lbtitle;
    private javax.swing.JLabel lbval1;
    private javax.swing.JLabel lbval2;
    private javax.swing.JLabel lbval3;
    // End of variables declaration//GEN-END:variables
}
